import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "./pos.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(props: Readonly<any>) {
  // console.log(props, "RootLayout");
  return (
    <html lang="en">
      <body className={inter.className}>{props.children}</body>
    </html>
  );
}
