import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import "@/assets/style";
import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
config.autoAddCss = false;

// const inter = Inter({ subsets: ["latin"] });

import {Roboto} from 'next/font/google'

const roboto = Roboto({
  subsets: ['latin'],
  weight : ['900']
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(props: Readonly<any>) {
  return (
    <html lang="en">
      <body>
        {/* {props.nav} */}
        {props.children}
      </body>
    </html>
  );
}
